project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: src/locales
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /en-US/en-US.json
    translation: /%locale%/%locale%.json
