project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 
files:
  - source: src/locales/en-US/en-US.json
    translation: src/locales/%locale%/%locale%.json
